### ISSUE TITLE
Parsing Trace categories for action that involves button click, page load, and wait for element to display

### ISSUE THREAD

**Issue by whsiao** [GoogleChrome/node-big-rig#10] opened 2016-01-14 21:39 UTC
Hello,

I have been tinkering around with node-big-rig and big-rig to get performance data with automation.  I have been successful in getting the data, but I have notice that one of the timelines that I labeled is not being recognized by node-big-rig as an action.

The timelines involves a button being clicked, wait for the page to load, and waiting for a specific element to appear.  The goal is to get the performance data of assets, files, rendering being loaded after a button is clicked to when the element appears in the browser after page refreshes.  BigRig does not recognize that kind of timeline as an action.

List of timelines that is labeled in the attached trace json file:
clickProfile
clickHomeLogin
clickLogin - bigRig cannot parse as action
inputUsername
inputPassword

Attach is the trace file that was recorded by the automation system.
BigRig version used to parse the trace file: 1.0.10

[trace7a.txt](https://github.com/GoogleChrome/node-big-rig/files/91035/trace7a.txt)
Note: Convert the file back to .json if needed.

**Comment by paullewis** [comment] 2016-01-14 21:51
Thanks for the report. I tried pulling the JSON into DevTools Timeline, and it doesn't show an area in the Console row for clickLogin. Is the code definitely calling `console.time('clickLogin')` and `console.timeEnd('clickLogin')`?

**Comment by sroussey** [comment] 2016-01-14 23:55
The issue is the page load. console.time and timeEnd don't work across pages.

**Comment by whsiao** [comment] 2016-01-14 23:58
@sroussey Pretty much what he said.

**Comment by paullewis** [comment] 2016-01-15 10:25
Ohhhh I see. Sorry, I missed that. Yes, you're right, Chrome doesn't support `time` and `timeEnd` across navigations. Unfortunately, then, I'll have to close this as not being a bug in Big Rig so much as it's a feature that's missing from Chrome and DevTools.

**Closed as completed by paullewis** 2016-01-15 10:25 UTC
